# Generated by Django 6.1.1 on 2026-09-04 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Administrator'), ('academic_manager', 'Academic Manager'), ('instructor', 'Instructor'), ('student', 'Student'), ('content_manager', 'Content Manager'), ('support_staff', 'Support Staff')], default='student', max_length=20),
        ),
    ]
