# Generated by Django 6.1.1 on 2026-09-10 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_passwordresettoken_user_user_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture_url',
            field=models.URLField(blank=True, help_text='External image URL — takes priority over an uploaded profile picture file when set.'),
        ),
    ]
