# Generated by Django 6.1.1 on 2026-09-16 19:07

from django.db import migrations, models


def disable_two_factor_for_existing_users(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    User.objects.filter(two_factor_enabled=True).update(two_factor_enabled=False)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_profile_picture_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='two_factor_enabled',
            field=models.BooleanField(default=False, help_text='Whether email-based 2FA is required at login for this account.'),
        ),
        migrations.RunPython(disable_two_factor_for_existing_users, migrations.RunPython.noop),
    ]
