# Generated by Django 6.1.1 on 2026-09-20 06:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_two_factor_enabled_default_false'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_code', models.CharField(choices=[('RWF', 'Rwandan Franc (RWF)'), ('USD', 'US Dollar ($)'), ('EUR', 'Euro (€)'), ('GBP', 'British Pound (£)'), ('KES', 'Kenyan Shilling (KSh)'), ('UGX', 'Ugandan Shilling (USh)'), ('TZS', 'Tanzanian Shilling (TSh)'), ('NGN', 'Nigerian Naira (₦)'), ('ZAR', 'South African Rand (R)'), ('GHS', 'Ghanaian Cedi (GH₵)')], default='RWF', max_length=3)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Platform Settings',
                'verbose_name_plural': 'Platform Settings',
            },
        ),
    ]
