# Generated by Django 6.1.1 on 2026-09-23 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_platformsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auth_provider',
            field=models.CharField(choices=[('password', 'Password'), ('google', 'Google')], default='password', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='google_id',
            field=models.CharField(blank=True, help_text="Google's `sub` claim — set once this account is linked to a Google Sign-In identity.", max_length=64, null=True, unique=True),
        ),
    ]
