# Generated by Django 6.1.1 on 2026-09-24 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_auth_provider_user_google_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructorprofile',
            name='linkedin_url',
            field=models.URLField(blank=True),
        ),
    ]
