# Generated by Django 6.1.1 on 2026-09-10 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_finalize_course_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='thumbnail_url',
            field=models.URLField(blank=True, help_text='External image URL — takes priority over an uploaded thumbnail/image file when set.'),
        ),
    ]
