# Generated by Django 6.1.1 on 2026-09-10 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_course_thumbnail_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='certificate_validity_months',
            field=models.PositiveIntegerField(blank=True, help_text='Months before an issued certificate expires. Leave blank for no expiry.', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='prerequisite',
            field=models.ForeignKey(blank=True, help_text='A student must complete this course before they can enroll.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unlocks', to='courses.course'),
        ),
        migrations.AddField(
            model_name='course',
            name='sequential_progression',
            field=models.BooleanField(default=False, help_text='When enabled, a lesson stays locked until the previous one in the course is completed.'),
        ),
    ]
