# Generated by Django 6.1.1 on 2026-09-04 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='allowed_file_types',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='assignment',
            name='instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='late_penalty',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Percentage deducted per late submission.', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='lessons.lesson'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='max_file_size',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum file size in KB.', null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='submission_type',
            field=models.CharField(choices=[('file', 'File'), ('text', 'Text'), ('file_and_text', 'File and Text')], default='file_and_text', max_length=20),
        ),
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('late', 'Late'), ('graded', 'Graded'), ('returned', 'Returned'), ('resubmitted', 'Resubmitted')], default='submitted', max_length=20),
        ),
    ]
