# Generated by Django 6.1.1 on 2026-09-20 07:08

import payments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_payment_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='currency',
            field=models.CharField(default=payments.models.default_currency, max_length=10),
        ),
    ]
