# Generated by Django 6.1.1 on 2026-09-04 10:02

from django.db import migrations, models


def normalize_meeting_platform(apps, schema_editor):
    """Existing rows (seeded before the choices field existed) used free-text
    values like 'Zoom' — normalize to the new lowercase choice keys so they
    keep validating on future writes."""
    LiveSession = apps.get_model('live_classes', 'LiveSession')
    mapping = {'zoom': 'zoom', 'google meet': 'google_meet', 'teams': 'teams', 'microsoft teams': 'teams'}
    for session in LiveSession.objects.all():
        normalized = mapping.get((session.meeting_platform or '').strip().lower(), 'other')
        if session.meeting_platform != normalized:
            session.meeting_platform = normalized
            session.save(update_fields=['meeting_platform'])


class Migration(migrations.Migration):

    dependencies = [
        ('live_classes', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(normalize_meeting_platform, migrations.RunPython.noop),
        migrations.AddField(
            model_name='livesession',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livesession',
            name='timezone',
            field=models.CharField(default='UTC', max_length=64),
        ),
        migrations.AlterField(
            model_name='livesession',
            name='meeting_platform',
            field=models.CharField(choices=[('zoom', 'Zoom'), ('google_meet', 'Google Meet'), ('teams', 'Microsoft Teams'), ('other', 'Other')], default='zoom', max_length=20),
        ),
        migrations.AlterField(
            model_name='livesession',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('live', 'Live'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('postponed', 'Postponed')], default='scheduled', max_length=20),
        ),
    ]
