# Generated by Django 6.1.1 on 2026-09-23 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_classes', '0002_livesession_capacity_livesession_timezone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livesession',
            name='jitsi_room',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='livesession',
            name='meeting_platform',
            field=models.CharField(choices=[('in_app', 'In-App (Asa Academy)'), ('zoom', 'Zoom'), ('google_meet', 'Google Meet'), ('teams', 'Microsoft Teams'), ('other', 'Other')], default='zoom', max_length=20),
        ),
    ]
