# Generated by Django 6.1.1 on 2026-09-10 14:21

from django.db import migrations

BADGES = [
    ('first_course_completed', 'First Steps', 'Completed your very first course.', '🎯'),
    ('course_completed', 'Course Complete', 'Completed a course.', '🏁'),
    ('perfect_quiz_score', 'Perfect Score', 'Scored 100% on a quiz or exam.', '💯'),
    ('five_courses_completed', 'High Achiever', 'Completed 5 courses.', '🏆'),
    ('certificate_earned', 'Certified', 'Earned a course certificate.', '📜'),
]


def seed_badges(apps, schema_editor):
    Badge = apps.get_model('certificates', 'Badge')
    for trigger, name, description, icon in BADGES:
        Badge.objects.get_or_create(trigger=trigger, defaults={'name': name, 'description': description, 'icon': icon})


def remove_badges(apps, schema_editor):
    Badge = apps.get_model('certificates', 'Badge')
    Badge.objects.filter(trigger__in=[b[0] for b in BADGES]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0002_badge_certificate_expires_at_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_badges, remove_badges),
    ]
